### PR TITLE
Remove moneybadger shop, add konsensus network

### PR DESCRIPTION
**Pull request by omnifinn**
I made this change earlier but somehow it was reverted, so here it is again.

### CODE REVIEW

**Comment by 6102bitcoin** [comment]
Not sure how that happened. 

Why remove moneybadger.shop ?

**Comment by omnifinn** [comment]
I am shutting it down because there has been no sales in 2 years. Also there are many better apparel shops out there already and I'm focusing on publishing through Konsensus Network.

Best:
Niko Laamanen
https://konsensus.network
https://t.me/omnifinn

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by 6102bitcoin** [comment]
Makes sense. Thanks for the heads up.

**Comment by omnifinn** [comment]
My pleasure, thanks for the merge! Appreciate your work.

best:

Niko Laamanen
https://konsensus.network
https://t.me/omnifinn

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Pull request merged**
