### PR TITLE
Alphabetized #Learning Section in index.html

### PR DESCRIPTION
**Pull request by joe-rodgers**
alphabetized listings on https://bitcoin-only.com/#learning

### CODE REVIEW

**Comment by joe-rodgers** [comment]
This is my first pull request on Github, everything else I've committed have been comments. Please let me know if I am breaking protocol.

**Comment by 6102bitcoin** [comment]
Thanks Joe,
I'm on a mobile device (for a few more days) so I can't check this very easily. 
It might have to wait till I have a desktop to check it is all good and nothing has broken.
Thanks for making a pull!!

**Comment by PuraVlda** [comment]
Joe, great idea on this.  Going through site tonight, may not be bad we do this to other sections too!  What do you guys think?

**Comment by joe-rodgers** [comment]
I think it's a good idea, unless there's something that should have specific attention. 

I would have done more, but this was my first pr

**Comment by 6102bitcoin** [comment]
Yes, it's a good idea.

Let's hold off doing any more until I am back at my keyboard to check there are no breaking changes, otherwise it could become very complicated rebasing new pull requests (sorting alphabetically will change the line numbers).

**Comment by 6102bitcoin** [comment]
Gone through all tables on all pages and done this in one hit given the large amount of code changes it makes - It would be a nightmare to rebase any new commits. Thanks for the suggestion Joe, apologies that I didn't merge this one, it was difficult to figure out how to merge given that some of the code had changed since you made the commit.

**Pull request closed without merging**
