### PR TITLE
Update books.vue book list

### PR DESCRIPTION
**Pull request by onebitco**
The Bitcoin Standard, Inventing Bitcoin, Programming Bitcoin

three books translated in Korean.

### CODE REVIEW

**Comment by wiz** [comment]
You should remove me and Teruko from the Korean version of the book

**Comment by onebitco** [comment]
Didnt realize translators were included there. Added translator for inventing bitcoin.

**Comment by 6102bitcoin** [comment]
Some of the sites linked are http only. Are they well known / legitimate?

**Comment by onebitco** [comment]
Yeah yes24 and kyobo are very well known but you have a good point.

Just replaced all the http bookstores.

**Comment by 6102bitcoin** [comment]
Book store links are still http.

**Comment by 6102bitcoin** [comment]
Links redirect. Can merge if https is used (https://www.gmarket.co.kr/)

**Pull request closed without merging**
