### PR TITLE
Add Shockwallet

### PR DESCRIPTION
**Pull request by capitalistdog**
add Shockwallet

### CODE REVIEW

**Comment by pardus79** [comment]
Looks interesting and appears to be bitcoin-only.

Since it is new and the website doesn't have a lot of information. I think user feedback should be requested on twitter and/or hold adding this due to being a new wallet.

**Comment by 6102bitcoin** [comment]
Agreed.

**Comment by 6102bitcoin** [comment]
Made [tweet](https://twitter.com/BitcoinOnly_/status/1340628806764257280?s=19) asking for feedback

**Comment by 6102bitcoin** [comment]
No feedback. Closing pull.

**Pull request closed without merging**
