### PR TITLE
add ministry of nodes, tftc, & ioni to videos

### PR DESCRIPTION
**Pull request by psychedelicbart**
add ministry of nodes, tftc, & ioni to videos

this covers:
Content Suggestion: loni appelberg #303 

Content Suggestion: ministry of nodes videos #304 

removed #305

### CODE REVIEW

**Comment by 6102bitcoin** [comment]
Thanks - I need to review a couple of these first as indicated in the issues.

**Comment by wiz** [comment]
@psychedelicbart in the future can you squash your work commits into a single commit before opening a PR :)

**Comment by psychedelicbart** [comment]
@wiz ok, gotcha. my bad, i is noob

**Comment by 6102bitcoin** [comment]
Just watched the latest BTCSessions video. If it were a website with the things listed below it would not be eligible for listing. For this reason, I think we should not list it. Thoughts @wiz @pardus79 

- Sponsored by Cobo Vault (Hardware wallet that supports altcoins and is not listed) although he does recommend the bitcoin-only firmeware.
- Covers an exchange which sells altcoins although he does just reference them as other coins and reaffirm that his is focused on bitcoin. There are other exchanges in Canada. At the current time Bull bitcoin price is 14,690 CAD **BUT** the exchange he covers is 14,479 CAD,

**Comment by pardus79** [comment]
If a podcasts advocates the use of Btcpayserver or Trezor (which both support alts) for bitcoin use should they be removed?

I think if a podcast recommends using multi-coin services for only bitcoin uses, that should be considered on a case by case basis.

I listen to BTC Sessions regularly. The show is bitcoin only in my experience and only mentions alts in passing or to point-out the downsides of them, just like most other bitcoin pods do.

**Comment by wiz** [comment]
ideally the additions should be in separate PRs so we can merge the ones that have consensus and reject the ones that don't

**Comment by 6102bitcoin** [comment]
This podcast is sponsored by altcoin supporting companies & the latest episode is promoting and guiding users through using an altcoin selling exchange. 

@psychedelicbart please can you remove BTCsessions from the pull.

**Comment by psychedelicbart** [comment]
Done

**Comment by 6102bitcoin** [comment]
Thanks!

**Pull request merged**
