### PR TITLE
Add Dutch podcast Beginnen met Bitcoin

### PR DESCRIPTION
**Pull request by AbelLykens**
Hope the list allows for non-English content? If not, close this. 

I added my Bitcoin-only podcast.

### CODE REVIEW

**Comment by pardus79** [comment]
ACK

**Comment by 6102bitcoin** [comment]
>  I know some Dutch bitcoin journalists + core dev for example who might vouch for me. Would that work?

That would be great - please ask them to either comment on this thread or they could tweet and you could post the link here.

Foreign language section sounds like a very sensible idea. We will add that then when you can do the above we will add your podcast.

Thanks,
6102

**Comment by M-BTC** [comment]
For what it's worth I can vouch for @AbelLykens. His podcast is Bitcoin only, definitely no shitcoin support/discussions.

**Comment by pardus79** [comment]
I used translate on their website and it was all bitcoin-only. Unable to verify if the actual podcast content is bitcoin-only.

**Comment by 6102bitcoin** [comment]
@AbelLykens please could you ask one of the Dutch bitcoin journalists + core devs you mentioned to comment or DM @bitcoinonly_ on twitter

**Comment by AbelLykens** [comment]
The guys over at bitcoinmagazine.nl (one of the larger news sites) confirmed it's bitcoin only: https://twitter.com/BitcoinMagNL/status/1307986366115065857 .

**Comment by AbelLykens** [comment]
Also Aaron van Wirdum (bitcoinmagazine.com) has [confirmed](https://twitter.com/AaronvanW/status/1307987093923266561).

**Comment by 6102bitcoin** [comment]
Please can you change this pull to add the podcast to the Dutch Section. Thank you.

**Comment by AbelLykens** [comment]
Continue in  #313 please ;)

**Pull request closed without merging**
