### PR TITLE
Content Suggestion: Bitcoindev.network

### PR DESCRIPTION
**Pull request by gr0kchain**
The Bitcoin Developer Network (BDN) is a community-driven project looking at educating the generation of Bitcoin developers. We invite developers, authors, editors, proofreaders, enthusiasts, subject matter experts and technical writers to get in touch so that we may reduce the barrier to entry in developing solutions at various layers of this technology.

### CODE REVIEW

**Comment by pardus79** [comment]
ACK

Nice site!

**Comment by 6102bitcoin** [comment]
I think this should be in the dev-tools page

**Comment by gr0kchain** [comment]
Interesting. I didn't bother checking the dev tool section. Should've grepped for it it. See it has already been added to the devtools section.

https://github.com/bitcoin-only/bitcoin-only/blob/df70f2168e2a908d2e0d35fec88e882ea590f5ce/pages/dev-tools.vue#L178

Seems a bit out of place though as this is more of an education site rather than software.

**Comment by 6102bitcoin** [comment]
I understand what you mean, the dev-tools page is a mixture of software and websites so I think this is the best place for it.

**Pull request closed without merging**
