### PR TITLE
Add KoinKeep iOS app

### PR DESCRIPTION
**Pull request by ddustin**

### CODE REVIEW

**Comment by 6102bitcoin** [comment]
Will wait for release before adding (July/December of 2020)

**Comment by wiz** [comment]
Yeah, I'd also like to see some more community support before adding a new wallet. There is a lot of trust in bitcoin-only.com and we need to properly vet any new wallets.

**Comment by 6102bitcoin** [comment]
As with the hardware wallet product, I would like to see some users vouching for this before adding. [tweet](https://twitter.com/BitcoinOnly_/status/1340744666912874498)

**Comment by 6102bitcoin** [comment]
As with the [hardware wallet product](https://github.com/bitcoin-only/bitcoin-only/pull/113), there was no feedback. Closing pull.

**Pull request closed without merging**
