### PR TITLE
Add RoninDojo

### PR DESCRIPTION
**Pull request by BitcoinQnA**

### CODE REVIEW

**Comment by pardus79** [comment]
Closes #218

**Comment by BitcoinQnA** [comment]
They aren't all listed alphabetically? Example, Node Launcher comes after Thundroid.

I placed it next to Samourai Dojo as they are similar.

**Comment by pardus79** [comment]
Everything else on the site is alphabetical. I think Nodelauncher should be moved up. I'll submit a PR to correct it, if you can move Ronin after Raspi. Or if you want to keep it next to Samourai, recommend naming it Samourai RoninDojo.

**Comment by 6102bitcoin** [comment]
Great - Thanks @pardus79 & @BitcoinQnA

**Pull request merged**
