### PR TITLE
Add Strike

### LINKED ISSUE #169: Content Suggestion: Strike
1) Link to Content: https://strike.zaphq.io/
2) Briefly Describe Content: Buy LN bitcoin.
3) Suggested Section: Get Bitcoin - Buy

More info: https://medium.com/@JimmyMow/announcing-strike-by-zap-4f578c7c8984

Still in beta. Recommend waiting until launch to add.

### PR DESCRIPTION
**Pull request by pardus79**
Added to both Buy Bitcoin and Spend Bitcoin>Tools

Closes #169

### CODE REVIEW

**Comment by wiz** [comment]
I'm confused, isn't this a USD debit card, more like a banking service?

**Comment by pardus79** [comment]
Instantly convert USD to lightning bitcoin. Load with USD. Scan lightning invoice. It pays it.

Since you can use it to send lightning to yourself, you can use it to effectively buy bitcoin. I've been using it since March.

Here's the original Medium article announcing it. https://medium.com/@JimmyMow/announcing-strike-by-zap-4f578c7c8984

**Comment by 6102bitcoin** [comment]
I agree with adding it to the buy bitcoin section but I disagree with adding it to the spend bitcoin section.

**Comment by pardus79** [comment]
Ok. I've removed from Spend section.

**Pull request merged**
