### PR TITLE
Add Voltage to Wallets page

### PR DESCRIPTION
**Pull request by gkrizek**
Thank you for creating the site! I'm proposing the addition of [Voltage](https://getvoltage.io) to the Wallets page. Let me know if you have questions or modifications. Thanks!

### CODE REVIEW

**Comment by 6102bitcoin** [comment]
Not a wallet. At most it could be a note on the page. 

Longer term it might be better to add a dedicated node page.

**Comment by 6102bitcoin** [comment]
@gkrizek please can you change this pull to add to the services section on the get-bitcoin page.

**Comment by gkrizek** [comment]
@6102bitcoin sure, I can update it. But I don’t really see a category that makes sense on that page. You can’t buy Bitcoin on Voltage, it’s simply a node provider. That’s why I thought Wallets might be a better place, but I agree that a dedicated nodes page would be best.

**Comment by 6102bitcoin** [comment]
Sorry - I meant the spend-bitcoin page. https://bitcoin-only.com/#spend-bitcoin

**Comment by gkrizek** [comment]
Hey @6102bitcoin, I just pushed changes and moved the Voltage section to the Spend Bitcoin page instead. Let me know what you think. Thanks!

**Comment by 6102bitcoin** [comment]
Thank you

**Pull request merged**
