### PR TITLE
add Hexa to ios, android, and on-chain wallets list

### PR DESCRIPTION
**Pull request by Varunram**
reference issue: #257

### CODE REVIEW

**Comment by wiz** [comment]
After reviewing your website a bit more, I would like to clarify a few things:
* Did Hexa or BitHyve recently change its name?
* Has Hexa or BitHyve ever participated in an ICO?
* Has Hexa or BitHyve ever promoted altcoins?

**Comment by modl21** [comment]
As far as I am aware, the answer is no to all of the above. It is a relatively new project.

**Comment by Varunram** [comment]
Thank you @modl21, @wiz I would like to confirm Matt's observation:

1. Hexa or BitHyve have not changed names (from anything or to anything).
2. Hexa and BitHyve have never participated in ICOs, and never will
3. Hexa is a bitcoin only app and BitHyve is a bitcoin only company.

**Comment by wiz** [comment]
1) The reason I'm asking if you changed your name is because there is a link on your website to https://github.com/thecryptobee/Hexa-Wallet which redirects to https://github.com/bithyve/hexa indicating you changed your name from thecryptobee to bithyve, at least on GitHub.

2) The reason I'm asking if you ever promoted altcoins is because while watching the Vimeo video on your website, I noticed the Ethereum support in your wallet app. Obviously this would make it disqualified for listing on Bitcoin Only.
Screen Shot 2020-08-02 at 1 42 00

Due to the reasons above, and the fact that this is a relatively new project, I don't feel comfortable merging this PR right now. I'll leave it up to @6102bitcoin to decide.

**Comment by Varunram** [comment]
Thank you wiz for the observations, we indeed aren't that diligent in updating in our website. To answer your concerns,
1. Yes, we changed names from `thecryptobee` to `bithyve` on github because initially, it was only a couple of us investigating bitcoin wallets. This was changed to `bithyve` later on when we had a clear goal of where we wanted to head. You can checkout the company listing at https://beta.companieshouse.gov.uk/company/11373012. You can also check our prototype app [here](https://github.com/bithyve/MyMoneyApp)
2. This image is from a design prototype in late 2016, before we started working on the prototype in 2018. As you can see from our [first commit on hexa](https://github.com/bithyve/hexa/commits/development?after=fae405f8a7f16f9ce40a58c7423ff2dc7d10c430+3000&branch=development) and [the first commit on our prototype app](https://github.com/bithyve/MyMoneyApp/commits/master?after=077a127f3f709d6156cc15b8f921fd84fc08fe25+69&branch=master), we've never had Ethereum support for Hexa.

On your concern that the app is a relatively new project, taking a totally random sample set with due respect to all devs involved,
1. [Caravan was started in Nov 2019](https://github.com/unchained-capital/caravan/commits/master?after=617f78c9d223951ae33999ea7318b308b2b15085+34&branch=master)
2. [Fully Noded's TestFlight link is on the website](https://testflight.apple.com/join/PuFnSqgi) (and the TestFlight link doesn't work)
3. [Muun Wallet was started in Sept 2019](https://github.com/muun/falcon/commits/master)

As you can see from the link above, Hexa was started in Feb 2019.

**Comment by wiz** [comment]
Thanks for your responses, those are all very reasonable explanations, please understand I'm just doing due diligence 👍

Since your wallet is new, I think we can merge this PR in 6 months, which is typical for new projects if you look at other PRs with the `waiting` tag - talk to you then :)

**Comment by 6102bitcoin** [comment]
Will review from 01/02/2020

**Comment by 6102bitcoin** [comment]
We have added other wallets without the 6 month requirement. For this reason I think we should add Hexa.

I think we should add a [New] or [Beta] tag to any wallets which have been released within the past year. Thoughts @wiz ?

**Comment by wiz** [comment]
Sure, I haven't used the wallet personally but if Matt says it's good and nobody reported any issues in the past few months let's add them

**Comment by mjlamb** [comment]
I wouldn't add any wallet unless it is reproducible, Being open source is not good enough. Currently https://walletscrutiny.com/android/io.hexawallet.hexa/ has not been tested as it has too few users.

**Comment by 6102bitcoin** [comment]
We will add and have a note for new wallets.

@mjlamb that website lists 3 "reproducible" bitcoin only wallets. They don't do any audits making the reproducible label a broadly meaningless feature. Most apps undergo regular large updates, without auditing the full codebase and then auditing each release, reproducibility adds little benefit imo.

**Comment by modl21** [comment]
for what it's worth I like the idea of a beta/new tag in general for new wallets, makes sense to keep that tag on for at least two years in my opinion, seems better to be conservative in that respect

**Comment by antuz123** [comment]
Thanks @wiz @Varunram @modl21 @6102bitcoin 

What do we now need to get Hexa listed on the site with a ‘new’ tag?

**Comment by 6102bitcoin** [comment]
Sorry for the delay. Added, I tweaked the description.

**Pull request merged**
