### PR TITLE
Adding KoinKeep to the list of hardware wallets.

### PR DESCRIPTION
**Pull request by ddustin**

### CODE REVIEW

**Comment by 6102bitcoin** [comment]
Will wait for release before adding (July/December of 2020).

**Comment by wiz** [comment]
Yeah, I'd also like to see some more community support before adding a new wallet. There is a lot of trust in bitcoin-only.com and we need to properly vet any new wallets.

**Comment by 6102bitcoin** [comment]
Little to no community support for this product. I have [tweeted](https://twitter.com/BitcoinOnly_/status/1340744666912874498) to see if anyone is using these.

**Comment by 6102bitcoin** [comment]
No feedback. Closing issue.

**Pull request closed without merging**
