### PR TITLE
Buy: Add Sparkswap

### PR DESCRIPTION
**Pull request by pardus79**

### CODE REVIEW

**Comment by 6102bitcoin** [comment]
Unfortunately it uses an altcoin and is thus not bitcoin-only

**Comment by pardus79** [comment]
@6102bitcoin Reading through their Discord it sounds like their old software supported LTC but the current one is BTC only.

I'll research further.

**Comment by 6102bitcoin** [comment]
They use an altcoin on the stellar network called AnchorUSD. 
If this has changed please let me know and I'll re-open this issue.

**Comment by pardus79** [comment]
I contacted Sparkswap regarding this. They indicated that their service, on their end, is bitcoin only. However, they use a 3rd party exchange www.anchorusd.com API for payment processing. This exchange supports multiple coins and stablecoins. It is not clear if user funds ever touch any altcoins, but it is entirely possible they go straight from USD to BTC.

Seems like a grey area to me if Sparkswap should be included. But I think that if Cash App is included, maybe this should be. It is extremely likely that when one buys BTC on Cash App, the service is buying coins from an exchange that supports altcoins.

**Pull request closed without merging**
