### PR TITLE
Add Polar to Dev Tools

### PR DESCRIPTION
**Pull request by lukechilds**
One-click Bitcoin Lightning networks for local app development & testing

### CODE REVIEW

**Comment by pardus79** [comment]
Are the litecoin binaries that your project downloads in order to run c-lightning a required dependency in order to run c-lightning with your tool? Or could this be removed from your project to make it only support bitcoin and still work with c-lightning?

https://github.com/jamaljsr/polar/search?q=litecoin&unscoped_q=litecoin

**Comment by lukechilds** [comment]
Ah, I hadn't realised that, it's not my project, it's built by @jamaljsr.

I doubt he would want to remove that. I'd still consider it worthwhile listing on the site, it's a great dev resource and it's definitely "Bitcoin focused".

I guess LTC would be useful for developing LN based cross chain atomic swaps.

But yeah, I hadn't realised it wasn't strictly "Bitcoin only" so understand if you guys don't wanna list it.

**Comment by jamaljsr** [comment]
@lukechilds thanks for suggesting to add Polar to the list here. 👍 

@pardus79 the `Dockerfile` in the Polar repo is just a copy of the `Dockerfile` from the c-lightning repo with a few minor tweaks to make it functional with Polar. See https://github.com/ElementsProject/lightning/blob/master/Dockerfile. The only thing it does is download and install the `litecoin-cli` binary into the docker container. c-lightning needs this "if" a user were to decide to use c-lightning on the litecoin chain. I didn't take this portion out because I'd like to keep the `Dockerfile` closely synced with the original course. The `litecoin-cli` binary is never executed when using Polar. It is not even possible to use it because Polar does not support `litecoind` backend nodes.

FYI: I personally am only interested in building tools for Bitcoin.

**Comment by wiz** [comment]
Many well respected Bitcoin projects such as BTCPay and Bisq are disqualified from being listed on Bitcoin-Only.com because they support altcoins. I'm afraid if your project supports Litecoin then it is also not eligible.

**Comment by jamaljsr** [comment]
Fair enough. I can always remove the litecoin binary in the future and resubmit to this repo, if this is the only issue.

**Comment by wiz** [comment]
Sounds good to me, let us know when you remove it :)

**Pull request closed without merging**
